[workspace]
members = ["http"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Onoal/fabric-standard"

[workspace.dependencies]
fabric = { package = "onoal-fabric", version = "1.0.0", path = "../../../Fabric/oss/fabric/sdk" }
fabric-composition-http-server = { package = "onoal-fabric-composition-http-server", version = "0.1.0", path = "../fabric-packages/compositions/web/http-server" }
fabric-package-key-value = { package = "onoal-fabric-package-key-value", version = "0.1.0", path = "../fabric-packages/packages/data/key-value" }
fabric-package-networking-http = { package = "onoal-fabric-package-networking-http", version = "0.1.0", path = "../fabric-packages/packages/networking/http" }
fabric-package-networking-tcp = { package = "onoal-fabric-package-networking-tcp", version = "0.1.0", path = "../fabric-packages/packages/networking/tcp" }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[patch.crates-io]
onoal-fabric = { path = "../../../Fabric/oss/fabric/sdk" }
