[package]
name = "onoal-fabric-standard-http"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Fabric Standard HTTP developer framework built on Fabric"
readme = "README.md"

[lib]
name = "fabric_standard_http"
path = "src/lib.rs"

[dependencies]
fabric.workspace = true
fabric-package-key-value.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
